### PR TITLE
Add installation guide for developer

### PR DESCRIPTION
**Pull request by Masao-Someki**
This PR adds installation guide for developers of this repository.

### CODE REVIEW

**Comment by karthik19967829** [comment]
Thanks , a couple of thoughts:
1. We can add torch and espnet versions 
2. S3PRL/Fairseq tested commit ids can be added similar to espnet installation

**Comment by Masao-Someki** [comment]
@karthik19967829 
Sorry for the late reply.
Do you mean that we need to specify the version of torch, espnet, and s3prl/fairseq in requirements_export.txt?

**Comment by karthik19967829** [comment]
@Masao-Someki yes if we specify the tested version that would be helpful for the developers to start with stable version

**Comment by Masao-Someki** [comment]
The detailed developer's guide should include the generic encoder. So with this PR, I will merge it with the additional demonstration.

**Pull request merged**
